In [2]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

data = pd.read_csv('../new_data/SeriesList.csv')

In [3]:
# ajout une colonne pour le type de la serie_status qui est à nan par défaut
data['status_series'] = np.nan

In [4]:
data.head()

      name_series  status_series
0         Private            NaN
1   Timeless Love            NaN
2  Above the Line            NaN
3      Pendergast            NaN
4         Astérix            NaN

In [5]:
data2 = pd.read_csv('../new_data/books_corrected.csv')
data2.head()

# keep only the columns that we need (title and series)
data2 = data2[['title', 'series']]
data2.head()

/tmp/ipykernel_36639/3507156580.py:1: DtypeWarning: Columns (18,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86) have mixed types. Specify dtype option on import or set low_memory=False.
  data2 = pd.read_csv('../new_data/books_corrected.csv')

                                               title               series
0                                       Inner Circle         (Private #5)
1                                  A Time to Embrace   (Timeless Love #2)
2                                           Take Two  (Above the Line #2)
3                                          Reliquary      (Pendergast #2)
4  The Millionaire Next Door: The Surprising Secr...                  NaN

In [6]:
#delete all the NaN values of series
data2 = data2.dropna(subset=['series'])

# Delete the parenthesis from the string

data2['series'] = data2['series'].str.strip('()')

# Split the string at ' #' and take the first part
data2['series'] = data2['series'].str.split('#').str[0]

# rename the column to "series_name"
data2 = data2.rename(columns={'series': 'series_name'})

data2.head()

               title      series_name
0       Inner Circle         Private
1  A Time to Embrace   Timeless Love
2           Take Two  Above the Line
3          Reliquary      Pendergast
8   Asterix the Gaul         Astérix

In [7]:

## URL de la base de données Supabase
database_url = 'postgresql://postgres.pczyoeavtwijgtkzgcaz:D0jVgaoGmDAFuaMS@aws-0-eu-west-3.pooler.supabase.com:6543/postgres'

## Créer une connexion avec la base de données
engine = create_engine(database_url)

## Insérer les données dans la table SQL 'author'
data.to_sql('series', con=engine, if_exists='append', index=False)

print("Insertion des données terminée.")

DataError: (psycopg2.errors.SequenceGeneratorLimitExceeded) nextval: reached maximum value of sequence "smallint_sequence" (32767)

[SQL: INSERT INTO series (name_series, status_series) VALUES (%(name_series__0)s, %(status_series__0)s), (%(name_series__1)s, %(status_series__1)s), (%(name_series__2)s, %(status_series__2)s), (%(name_series__3)s, %(status_series__3)s), (%(name_series__4)s ... 47483 characters truncated ... 7)s), (%(name_series__998)s, %(status_series__998)s), (%(name_series__999)s, %(status_series__999)s)]
[parameters: {'name_series__0': 'Private', 'status_series__0': None, 'name_series__1': 'Timeless Love', 'status_series__1': None, 'name_series__2': 'Above the Line', 'status_series__2': None, 'name_series__3': 'Pendergast', 'status_series__3': None, 'name_series__4': 'Astérix', 'status_series__4': None, 'name_series__5': 'Winnie-the-Pooh', 'status_series__5': None, 'name_series__6': 'The Cinder Spires', 'status_series__6': None, 'name_series__7': "Mario Puzo's Mafia", 'status_series__7': None, 'name_series__8': 'Halfblood Chronicles', 'status_series__8': None, 'name_series__9': 'Silence', 'status_series__9': None, 'name_series__10': 'All My Love, Detrick', 'status_series__10': None, 'name_series__11': 'New Species', 'status_series__11': None, 'name_series__12': 'Firebird', 'status_series__12': None, 'name_series__13': 'Mary Russell and Sherlock Holmes', 'status_series__13': None, 'name_series__14': 'Psy-Changeling', 'status_series__14': None, 'name_series__15': 'Circle of Magic', 'status_series__15': None, 'name_series__16': 'The Circle Reforged', 'status_series__16': None, 'name_series__17': 'Cody Gunner', 'status_series__17': None, 'name_series__18': 'Leven Thumps', 'status_series__18': None, 'name_series__19': 'The Princess Diaries', 'status_series__19': None, 'name_series__20': 'Tomorrow', 'status_series__20': None, 'name_series__21': 'Théâtre Illuminata', 'status_series__21': None, 'name_series__22': 'The Killing of Historical Figures', 'status_series__22': None, 'name_series__23': 'Through a Glass Darkly', 'status_series__23': None, 'name_series__24': 'Wind on Fire', 'status_series__24': None ... 1900 parameters truncated ... 'name_series__975': 'Lace', 'status_series__975': None, 'name_series__976': 'A Song of Ice and Fire', 'status_series__976': None, 'name_series__977': 'The Book of the New Sun', 'status_series__977': None, 'name_series__978': 'Violet Eyes', 'status_series__978': None, 'name_series__979': 'Camille', 'status_series__979': None, 'name_series__980': 'Hana-Kimi', 'status_series__980': None, 'name_series__981': 'Camel Club', 'status_series__981': None, 'name_series__982': 'The Children of the Red King', 'status_series__982': None, 'name_series__983': 'FunJungle', 'status_series__983': None, 'name_series__984': 'Circle Trilogy', 'status_series__984': None, 'name_series__985': 'The Vampire Diaries', 'status_series__985': None, 'name_series__986': 'The Iron Fey', 'status_series__986': None, 'name_series__987': 'The Fallen', 'status_series__987': None, 'name_series__988': 'Dan and Elle', 'status_series__988': None, 'name_series__989': 'Dragon Keeper', 'status_series__989': None, 'name_series__990': 'Zombie Fallout', 'status_series__990': None, 'name_series__991': 'The Vampire Diaries: The Hunters', 'status_series__991': None, 'name_series__992': 'خواطر أحمد الشقيري', 'status_series__992': None, 'name_series__993': 'Goddess War', 'status_series__993': None, 'name_series__994': 'The Dark Elements', 'status_series__994': None, 'name_series__995': 'Colonel Race', 'status_series__995': None, 'name_series__996': 'Never Been', 'status_series__996': None, 'name_series__997': 'Pídeme lo que quieras', 'status_series__997': None, 'name_series__998': 'Secrets of Shadow Hill', 'status_series__998': None, 'name_series__999': "Bloom's Notes", 'status_series__999': None}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)

In [8]:
import pandas as pd
from sqlalchemy import create_engine, select, Table, MetaData
from sqlalchemy.orm import sessionmaker

# Connexion à la base de données
engine = create_engine(database_url)
Session = sessionmaker(bind=engine)
session = Session()

# Créer l'objet MetaData sans `bind`
metadata = MetaData()

# Charger les tables book et awards en utilisant `autoload_with=engine`
book_table = Table('book', metadata, autoload_with=engine)
series_table = Table('series', metadata, autoload_with=engine)

# Requête pour obtenir les IDs de livres et awards selon leurs noms
def get_id_by_name(table, name_column, name_value, search_column='id'):
    result = session.execute(select(table.c[search_column]).where(table.c[name_column] == name_value)).first()
    return result[0] if result else None

# Parcours du DataFrame pour récupérer les IDs et afficher un message après chaque insertion dans `associations`
associations = []
for index, row in data2.iterrows():
    book_id = get_id_by_name(book_table, 'title', row['title'], search_column='id_book')
    series_id = get_id_by_name(series_table, 'name_series', row['series_name'], search_column='id_series')
    
    # Vérifie que les deux IDs existent avant de les insérer
    if book_id and series_id:
        associations.append({'id_book': book_id, 'id_series': series_id})
        print(f"Association ajoutée : livre ID {book_id}, series ID {series_id}")

# sauvegarder les associations dans un fichier csv
df_associations = pd.DataFrame(associations)
df_associations.to_csv('associationsSeries.csv', index=False)


# Charger les associations depuis le fichier CSV
associations = pd.read_csv('associations.csv')

# renommer les colonnes
associations = associations.rename(columns={'book_id': 'id_book', 'series_id': 'id_series'})

# enlever les doublons de (id_book, id_award)
associations = associations.drop_duplicates()

display(associations.head())

# Insérer les associations dans la table SQL 'book_award'
associations.to_sql('book_series', con=engine, if_exists='append', index=False)


# Ferme la session après insertion
session.close()

Association ajoutée : livre ID 15, series ID 18322
Association ajoutée : livre ID 49, series ID 18337
Association ajoutée : livre ID 42960, series ID 18390
Association ajoutée : livre ID 139, series ID 18392
Association ajoutée : livre ID 147, series ID 18397
Association ajoutée : livre ID 308, series ID 18476
Association ajoutée : livre ID 668, series ID 18589
Association ajoutée : livre ID 699, series ID 18605
Association ajoutée : livre ID 763, series ID 18625
Association ajoutée : livre ID 878, series ID 18659
Association ajoutée : livre ID 897, series ID 18667
Association ajoutée : livre ID 946, series ID 18602
Association ajoutée : livre ID 1012, series ID 20400
Association ajoutée : livre ID 1020, series ID 18713
Association ajoutée : livre ID 1055, series ID 18729
Association ajoutée : livre ID 1069, series ID 18733
Association ajoutée : livre ID 1085, series ID 18743
Association ajoutée : livre ID 1128, series ID 18753
Association ajoutée : livre ID 1131, series ID 24690
Association ajoutée : livre ID 1137, series ID 18758
Association ajoutée : livre ID 1256, series ID 18804
Association ajoutée : livre ID 1362, series ID 18831
Association ajoutée : livre ID 1378, series ID 18729
Association ajoutée : livre ID 1484, series ID 18870
Association ajoutée : livre ID 1516, series ID 18882
Association ajoutée : livre ID 1549, series ID 18892
Association ajoutée : livre ID 1563, series ID 18897
Association ajoutée : livre ID 1622, series ID 18919
Association ajoutée : livre ID 1679, series ID 18945
Association ajoutée : livre ID 1695, series ID 18955
Association ajoutée : livre ID 1737, series ID 18969
Association ajoutée : livre ID 1756, series ID 18602
Association ajoutée : livre ID 1783, series ID 18983
Association ajoutée : livre ID 1828, series ID 19006
Association ajoutée : livre ID 1919, series ID 19041
Association ajoutée : livre ID 1944, series ID 19048
Association ajoutée : livre ID 1948, series ID 19051
Association ajoutée : livre ID 1960, series ID 19057
Association ajoutée : livre ID 1978, series ID 19069
Association ajoutée : livre ID 2006, series ID 19085
Association ajoutée : livre ID 2014, series ID 19087
Association ajoutée : livre ID 2034, series ID 18602
Association ajoutée : livre ID 2084, series ID 19113
Association ajoutée : livre ID 2090, series ID 19116
Association ajoutée : livre ID 2113, series ID 19126
Association ajoutée : livre ID 2132, series ID 19136
Association ajoutée : livre ID 2176, series ID 19154
Association ajoutée : livre ID 2182, series ID 19155
Association ajoutée : livre ID 2270, series ID 19188
Association ajoutée : livre ID 2328, series ID 19207
Association ajoutée : livre ID 2539, series ID 19282
Association ajoutée : livre ID 2624, series ID 19314
Association ajoutée : livre ID 23707, series ID 19334
Association ajoutée : livre ID 2676, series ID 19335
Association ajoutée : livre ID 2685, series ID 19341
Association ajoutée : livre ID 2687, series ID 18373
Association ajoutée : livre ID 2714, series ID 19351
Association ajoutée : livre ID 2716, series ID 18476
Association ajoutée : livre ID 2785, series ID 19376
Association ajoutée : livre ID 2788, series ID 19378
Association ajoutée : livre ID 2848, series ID 18602
Association ajoutée : livre ID 45153, series ID 19411
Association ajoutée : livre ID 2969, series ID 19446
Association ajoutée : livre ID 2987, series ID 19451
Association ajoutée : livre ID 3015, series ID 19460
Association ajoutée : livre ID 3028, series ID 19466
Association ajoutée : livre ID 3087, series ID 18761
Association ajoutée : livre ID 3157, series ID 19504
Association ajoutée : livre ID 3238, series ID 19538
Association ajoutée : livre ID 17445, series ID 24690
Association ajoutée : livre ID 3256, series ID 19542
Association ajoutée : livre ID 3365, series ID 19590
Association ajoutée : livre ID 3384, series ID 19601
Association ajoutée : livre ID 3397, series ID 19604
Association ajoutée : livre ID 3525, series ID 19653
Association ajoutée : livre ID 18816, series ID 24690
Association ajoutée : livre ID 3592, series ID 19680
Association ajoutée : livre ID 3609, series ID 19688
Association ajoutée : livre ID 3637, series ID 19696
Association ajoutée : livre ID 3661, series ID 19446
Association ajoutée : livre ID 3677, series ID 19710
Association ajoutée : livre ID 3692, series ID 19717
Association ajoutée : livre ID 3714, series ID 19723
Association ajoutée : livre ID 3723, series ID 19725
Association ajoutée : livre ID 3918, series ID 19814
Association ajoutée : livre ID 3998, series ID 19847
Association ajoutée : livre ID 4010, series ID 18955
Association ajoutée : livre ID 4055, series ID 19860
Association ajoutée : livre ID 4092, series ID 19873
Association ajoutée : livre ID 4287, series ID 18390
Association ajoutée : livre ID 4294, series ID 19947
Association ajoutée : livre ID 4335, series ID 19960
Association ajoutée : livre ID 4350, series ID 19965
Association ajoutée : livre ID 4402, series ID 19983
Association ajoutée : livre ID 4497, series ID 19334
Association ajoutée : livre ID 4586, series ID 20043
Association ajoutée : livre ID 4663, series ID 18955
Association ajoutée : livre ID 4668, series ID 20071
Association ajoutée : livre ID 4723, series ID 20086
Association ajoutée : livre ID 4736, series ID 19188
Association ajoutée : livre ID 4822, series ID 19188
Association ajoutée : livre ID 4907, series ID 20152
Association ajoutée : livre ID 4955, series ID 20166
Association ajoutée : livre ID 5039, series ID 20196
Association ajoutée : livre ID 5044, series ID 18758
Association ajoutée : livre ID 5185, series ID 20240
Association ajoutée : livre ID 5223, series ID 20256
Association ajoutée : livre ID 5254, series ID 19696
Association ajoutée : livre ID 5273, series ID 20272
Association ajoutée : livre ID 5302, series ID 19006
Association ajoutée : livre ID 5318, series ID 20289
Association ajoutée : livre ID 5434, series ID 19116
Association ajoutée : livre ID 5526, series ID 20352
Association ajoutée : livre ID 5559, series ID 19006
Association ajoutée : livre ID 5720, series ID 20398
Association ajoutée : livre ID 5760, series ID 20415
Association ajoutée : livre ID 5787, series ID 20422
Association ajoutée : livre ID 5810, series ID 20429
Association ajoutée : livre ID 5865, series ID 20445
Association ajoutée : livre ID 5929, series ID 20471
Association ajoutée : livre ID 5987, series ID 18831
Association ajoutée : livre ID 17731, series ID 20499
Association ajoutée : livre ID 6071, series ID 20516
Association ajoutée : livre ID 6074, series ID 19696
Association ajoutée : livre ID 6195, series ID 20551
Association ajoutée : livre ID 6197, series ID 20553
Association ajoutée : livre ID 6241, series ID 20445
Association ajoutée : livre ID 6243, series ID 19680
Association ajoutée : livre ID 6278, series ID 20576
Association ajoutée : livre ID 6340, series ID 20592
Association ajoutée : livre ID 6384, series ID 20601
Association ajoutée : livre ID 6517, series ID 20634
Association ajoutée : livre ID 6614, series ID 20653
Association ajoutée : livre ID 6665, series ID 20662
Association ajoutée : livre ID 6667, series ID 20663
Association ajoutée : livre ID 6698, series ID 20668
Association ajoutée : livre ID 6712, series ID 20673
Association ajoutée : livre ID 6727, series ID 20677
Association ajoutée : livre ID 6758, series ID 20686
Association ajoutée : livre ID 6822, series ID 18502
Association ajoutée : livre ID 6898, series ID 20727
Association ajoutée : livre ID 6945, series ID 20732
Association ajoutée : livre ID 7082, series ID 20756
Association ajoutée : livre ID 7136, series ID 20765
Association ajoutée : livre ID 7144, series ID 20768
Association ajoutée : livre ID 7203, series ID 20788
Association ajoutée : livre ID 7215, series ID 20792
Association ajoutée : livre ID 7273, series ID 20804
Association ajoutée : livre ID 7348, series ID 20822
Association ajoutée : livre ID 7364, series ID 20823
Association ajoutée : livre ID 7405, series ID 20828
Association ajoutée : livre ID 7425, series ID 20831
Association ajoutée : livre ID 7498, series ID 20852
Association ajoutée : livre ID 7537, series ID 20861
Association ajoutée : livre ID 7643, series ID 20883
Association ajoutée : livre ID 7721, series ID 20902
Association ajoutée : livre ID 7733, series ID 20905
Association ajoutée : livre ID 25003, series ID 24410
Association ajoutée : livre ID 8061, series ID 20994
Association ajoutée : livre ID 8101, series ID 21010
Association ajoutée : livre ID 8194, series ID 21031
Association ajoutée : livre ID 8206, series ID 21034
Association ajoutée : livre ID 8216, series ID 21036
Association ajoutée : livre ID 8461, series ID 20668
Association ajoutée : livre ID 8466, series ID 21104
Association ajoutée : livre ID 8468, series ID 21105
Association ajoutée : livre ID 8513, series ID 21120
Association ajoutée : livre ID 8561, series ID 21128
Association ajoutée : livre ID 17058, series ID 21960
Association ajoutée : livre ID 8604, series ID 21142
Association ajoutée : livre ID 15965, series ID 24690
Association ajoutée : livre ID 8639, series ID 21156
Association ajoutée : livre ID 8646, series ID 21159
Association ajoutée : livre ID 8716, series ID 21178
Association ajoutée : livre ID 8738, series ID 21182
Association ajoutée : livre ID 8789, series ID 21196
Association ajoutée : livre ID 8890, series ID 21232
Association ajoutée : livre ID 8960, series ID 21026
Association ajoutée : livre ID 9158, series ID 21299
Association ajoutée : livre ID 9281, series ID 21338
Association ajoutée : livre ID 9294, series ID 21340
Association ajoutée : livre ID 9381, series ID 21356
Association ajoutée : livre ID 9606, series ID 21404
Association ajoutée : livre ID 9663, series ID 21414
Association ajoutée : livre ID 9671, series ID 21416
Association ajoutée : livre ID 9712, series ID 19578
Association ajoutée : livre ID 9777, series ID 21440
Association ajoutée : livre ID 9862, series ID 21460
Association ajoutée : livre ID 9992, series ID 21489
Association ajoutée : livre ID 9993, series ID 21490
Association ajoutée : livre ID 10136, series ID 21519
Association ajoutée : livre ID 41977, series ID 21521
Association ajoutée : livre ID 10178, series ID 21524
Association ajoutée : livre ID 10240, series ID 21536
Association ajoutée : livre ID 10352, series ID 21560
Association ajoutée : livre ID 10601, series ID 20804
Association ajoutée : livre ID 10703, series ID 21639
Association ajoutée : livre ID 10765, series ID 21656
Association ajoutée : livre ID 10899, series ID 21679
Association ajoutée : livre ID 10912, series ID 21683
Association ajoutée : livre ID 4663, series ID 24410
Association ajoutée : livre ID 11117, series ID 20994
Association ajoutée : livre ID 11157, series ID 21010
Association ajoutée : livre ID 11173, series ID 21730
Association ajoutée : livre ID 11236, series ID 21034
Association ajoutée : livre ID 11409, series ID 20668
Association ajoutée : livre ID 11428, series ID 21802
Association ajoutée : livre ID 11468, series ID 21128
Association ajoutée : livre ID 11485, series ID 21812
Association ajoutée : livre ID 11658, series ID 21842
Association ajoutée : livre ID 11670, series ID 21844
Association ajoutée : livre ID 11745, series ID 21868
Association ajoutée : livre ID 11768, series ID 21876
Association ajoutée : livre ID 11774, series ID 21877
Association ajoutée : livre ID 11825, series ID 21159
Association ajoutée : livre ID 11832, series ID 18892
Association ajoutée : livre ID 11900, series ID 21906
Association ajoutée : livre ID 48105, series ID 21960
Association ajoutée : livre ID 12011, series ID 21928
Association ajoutée : livre ID 12055, series ID 21938
Association ajoutée : livre ID 12071, series ID 21943
Association ajoutée : livre ID 12134, series ID 21959
Association ajoutée : livre ID 12189, series ID 21970

KeyboardInterrupt: